spring:
  datasource:
    url: jdbc:postgresql://payment-db:5432/${PAYMENT_DB_NAME}
    username: ${PAYMENT_DB_USER}
    password: ${PAYMENT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
