spring:
  datasource:
    url: jdbc:postgresql://payment-db:5432/${PAYMENT_DB_NAME}
    username: ${PAYMENT_DB_USER}
    password: ${PAYMENT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

user-service:
  url: user-service

meeting-service:
  url: meeting-service

tutoring-service:
  url: tutoring-service

application:
  url: eduvy.pl