version: '3.8'

services:
  gateway:
    image: ${GATEWAY_IMAGE}
    build: ./gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - user-service
      - tutoring-service
      - chat-service
      - payment-service
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - USER_PORT=${USER_PORT}
      - TUTORING_PORT=${TUTORING_PORT}
      - CHAT_PORT=${CHAT_PORT}
      - PAYMENT_PORT=${PAYMENT_PORT}
    networks:
      - app-network

  user-service:
    image: ${USER_IMAGE}
    build: ./user-service
    ports:
      - "${USER_PORT}:${USER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - USER_PORT=${USER_PORT}
      - USER_DB_NAME=${USER_DB_NAME}
      - USER_DB_USER=${USER_DB_USER}
      - USER_DB_PASSWORD=${USER_DB_PASSWORD}
    depends_on:
      - user-db
    networks:
      - app-network

  tutoring-service:
    image: ${TUTORING_IMAGE}
    build: ./tutoring-service
    ports:
      - "${TUTORING_PORT}:${TUTORING_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - TUTORING_PORT=${TUTORING_PORT}
      - TUTORING_DB_NAME=${TUTORING_DB_NAME}
      - TUTORING_DB_USER=${TUTORING_DB_USER}
      - TUTORING_DB_PASSWORD=${TUTORING_DB_PASSWORD}
    depends_on:
      - tutoring-db
    networks:
      - app-network

  chat-service:
    image: ${CHAT_IMAGE}
    build: ./chat-service
    ports:
      - "${CHAT_PORT}:${CHAT_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - CHAT_PORT=${CHAT_PORT}
      - CHAT_DB_NAME=${CHAT_DB_NAME}
      - CHAT_DB_USER=${CHAT_DB_USER}
      - CHAT_DB_PASSWORD=${CHAT_DB_PASSWORD}
    depends_on:
      - chat-db
    networks:
      - app-network

  payment-service:
    image: ${PAYMENT_IMAGE}
    build: ./payment-service
    ports:
      - "${PAYMENT_PORT}:${PAYMENT_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - PAYMENT_PORT=${PAYMENT_PORT}
      - PAYMENT_DB_NAME=${PAYMENT_DB_NAME}
      - PAYMENT_DB_USER=${PAYMENT_DB_USER}
      - PAYMENT_DB_PASSWORD=${PAYMENT_DB_PASSWORD}
    depends_on:
      - payment-db
    networks:
      - app-network

  meeting-service:
    image: ${MEETING_IMAGE}
    build: ./meeting-service
    ports:
      - "${MEETING_PORT}:${MEETING_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - MEETING_PORT=${MEETING_PORT}
      - MEETING_DB_NAME=${MEETING_DB_NAME}
      - MEETING_DB_USER=${MEETING_DB_USER}
      - MEETING_DB_PASSWORD=${MEETING_DB_PASSWORD}
    depends_on:
      - meeting-db
    networks:
      - app-network

  user-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app-network

  tutoring-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${TUTORING_DB_USER}
      POSTGRES_PASSWORD: ${TUTORING_DB_PASSWORD}
      POSTGRES_DB: ${TUTORING_DB_NAME}
    volumes:
      - tutoring_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - app-network

  chat-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${CHAT_DB_USER}
      POSTGRES_PASSWORD: ${CHAT_DB_PASSWORD}
      POSTGRES_DB: ${CHAT_DB_NAME}
    volumes:
      - chat_db_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - app-network

  payment-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${PAYMENT_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASSWORD}
      POSTGRES_DB: ${PAYMENT_DB_NAME}
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - app-network

  meeting-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${MEETING_DB_USER}
      POSTGRES_PASSWORD: ${MEETING_DB_PASSWORD}
      POSTGRES_DB: ${MEETING_DB_NAME}
    volumes:
      - meeting_db_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      - app-network

networks:
  app-network:

volumes:
  user_db_data:
  tutoring_db_data:
  chat_db_data:
  payment_db_data:
  meeting_db_data: