spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope: openid profile email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: post
        provider:
          auth0:
            issuer-uri: https://YOUR_DOMAIN/

server:
  port: ${GATEWAY_PORT:8081}

logging:
  level:
    root: DEBUG
    io.netty: DEBUG