spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
        - id: tutoring-service
          uri: http://localhost:8085
          predicates:
            - Path=/tutoring/**
        - id: user-service-swagger
          uri: http://user-service:${USER_PORT:8083}
          predicates:
            - Path=/user-service/swagger-ui/**

auth0:
  audience: Bh6vvSbQlWvOGziA6cuKqpZdWIsU3LBt
  issuer: https://dev-gknidk2q1foe4txe.us.auth0.com/

server:
  port: 8081

