spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
        - id: tutoring-service
          uri: http://localhost:8085
          predicates:
            - Path=/tutoring/**
        - id: chat-service
          uri: http://localhost:8086 # Replace with the service name in your registry
          predicates:
            - Path=/ws/**
          filters:
            - RewritePath=/ws/(?<segment>.*), /${segment}
      default-filters:
        - PreserveHostHeader

auth0:
  audience: Bh6vvSbQlWvOGziA6cuKqpZdWIsU3LBt
  issuer: https://dev-gknidk2q1foe4txe.us.auth0.com/

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          socket: DEBUG
        messaging: DEBUG