spring:
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://localhost:${PAYMENT_PORT}
          predicates:
            - Path=/payment/**
        - id: user-service
          uri: http://localhost:${USER_PORT}
          predicates:
            - Path=/users/**
        - id: tutoring-service
          uri: http://localhost:${TUTORING_PORT}
          predicates:
            - Path=/tutoring/**
        - id: chat-service
          uri: http://localhost:${CHAT_PORT} # Replace with the service name in your registry
          predicates:
            - Path=/ws/**
          filters:
            - RewritePath=/ws/(?<segment>.*), /${segment}
      default-filters:
        - PreserveHostHeader

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          socket: DEBUG
        messaging: DEBUG