spring:
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: payment-service:${PAYMENT_PORT}
          predicates:
            - Path=/payment/**
        - id: user-service
          uri: http://user-service:${USER_PORT}
          predicates:
            - Path=/users/**
        - id: tutoring-service
          uri: http://tutoring-service:${TUTORING_PORT}
          predicates:
            - Path=/tutoring/**
        - id: chat-service
          uri: http://chat-service:${CHAT_PORT}
          predicates:
            - Path=/chat/**
