spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope: openid profile email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: post
        provider:
          auth0:
            issuer-uri: https://YOUR_DOMAIN/

  cloud:
    gateway:
      routes:
        - id: authorization-service
          uri: http://localhost:${AUTHORIZATION_PORT:8081}
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
        - id: tutoring-service
          uri: http://localhost:8085
          predicates:
            - Path=/tutoring/**
        - id: user-service-swagger
          uri: http://user-service:${USER_PORT:8083}
          predicates:
            - Path=/user-service/swagger-ui/**

auth0:
  audience: Bh6vvSbQlWvOGziA6cuKqpZdWIsU3LBt
  issuer: https://dev-gknidk2q1foe4txe.us.auth0.com/

server:
  port: ${GATEWAY_PORT:8081}

logging:
  level:
    root: DEBUG
    io.netty: DEBUG
