spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:${USER_PORT}
          predicates:
            - Path=/users/**
        - id: tutoring-service
          uri: http://tutoring-service:${TUTORING_PORT}
          predicates:
            - Path=/tutoring/**
        - id: payment-service
          uri: http://payment-service:${PAYMENT_PORT}
          predicates:
            - Path=/payment/**
        - id: chat-service
          uri: http://chat-service:${CHAT_PORT}
          predicates:
            - Path=/ws/**,/chat/**
          filters:
            - RewritePath=/ws/(?<segment>.*), /${segment}
      default-filters:
        - PreserveHostHeader

logging:
  level:
    root: DEBUG
    io.netty: DEBUG
    org:
      springframework:
        security: DEBUG
        web:
          socket: DEBUG
        messaging: DEBUG