spring:
  datasource:
    url: jdbc:postgresql://tutoring-db:5432/${TUTORING_DB_NAME}
    username: ${TUTORING_DB_USER}
    password: ${TUTORING_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

user-service:
  url: user-service:8083

meeting-service:
  url: meeting-service:8088

payment-service:
  url: payment-service:8087

application:
  url: eduvy.pl