spring:
  datasource:
    url: jdbc:postgresql://localhost:${MEETING_DB_PORT_LOCAL:5432}/${MEETING_DB_NAME_LOCAL:authorization_db_dev}
    username: ${MEETING_DB_USER:chat_user_dev}
    password: ${MEETING_DB_PASSWORD:chat_pass_dev}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
